Upkeep
poissonconsulting/dbflobr pull request #27
Opened 2024-09-19 04:40 UTC by dunkenwg

2024-09-19 15:05 UTC, joethorley requested changes
looks great - that is a really good PR! I just have one question.

2024-09-19 15:05 UTC, joethorley commented on tests/testthat/test-check.R
> +  expect_error(check_flob_query("non-blob", slob = TRUE), "`x` must be a blob of a serialized object.")
What happens if `slob = NA`

2024-11-04 20:45 UTC, dunkenwg commented
@joethorley, @sebdalgarno, and @evanamiesgalonski, when you have a chance would you be able to review this pull request?

2024-11-05 02:38 UTC, joethorley approved these changes
looks good - there is a conflict that presumably we can resolve when merge?

2024-11-05 15:26 UTC, dunkenwg commented
The conflict should be easy to resolve when we merge. It's just a difference in the README badges

2024-11-06 20:10 UTC, evanamiesgalonski approved these changes
Looks good to me. 
Once we've merged I'll do a pass through at some point and clean up some of the unit tests.

2024-11-06 23:03 UTC, sebdalgarno approved these changes
looks good thanks Duncan!

2024-11-07 00:24 UTC, merged